AuthFlow (#10)
* refactor: removing FlowBite and enhance RouterNavigate (#8)

* feat: adding shadcn styles (#9)

* feat: adding shadcn styles

* refactor: deleting old App Router and Folder Structures for one new.

* feat: adding loginPage with form.

* refactor/login-page

* refactor/login-page

* feat: adding form validations with zod and react hook forms.

* feat: adding form validations and reusable copmponents

* feat: adding form validations and reusable copmponents

* feat: adding protected and public route

* feature: loading spinner when auth is checking

* refactor: enhancing performance in the Auth Flow

* refactor: editing lint-staged to work correctly

---------

Co-authored-by: Emanuel <emanuelrojasguindan@gmail.com>

---------

Co-authored-by: Emanuel <emanuelrojasguindan@gmail.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,5 +5,26 @@ echo "🔍 Running formatting and style analysis before commit..."
 # Scripts
 npx lint-staged
 
+# Check for errors
+if [ $? -ne 0 ]; then
+    echo "❌ Formatting or style analysis failed. Please check your code and try again."
+    exit 1
+fi
+
+# Success message
+echo "✅ Formatting and style analysis passed. Your code is clean and shiny! 🚀"
+
+# # Run tests
+# npm run test
+
+# # Check for errors
+# if [ $? -ne 0 ]; then
+#     echo "❌ Tests failed. Please check your code and try again."
+#     exit 1
+# fi
+
+# # Success message
+# echo "✅ Tests passed. Your code is clean and shiny! 🚀"
+
 # End message
 echo "✅ All set. Your code is clean and shiny! 🚀"
